### ISSUE TITLE
Don't use sudo to build docker image

### ISSUE THREAD

**Issue by xrl** [bloomberg/goldpinger#15]
The docker cli should not need sudo to talk to the docker daemon. On a linux system you can do `sudo usermod -aG docker $USER` and you'll get access to the docker.sock (check the ownership of the sock to make sure you're doing the right usermod). On mac os x the docker for mac will set up `docker` properly, no sudo needed.

Open to a PR to fix this?

**Comment by seeker89** [comment]
Sure. We touched upon this [in the thread on HN](https://news.ycombinator.com/news), but due to popular demand I don't see why not drop it. Please don't forget the `-s` flag when committing, to make the DCO bot happy 😄
