### ISSUE TITLE
Should set GOOS in build/build.sh

### ISSUE THREAD

**Issue by xrl** [bloomberg/goldpinger#17]
I'm on a mac and I just cut a release of goldpinger, the pod is failing because the exectuable is the wrong format. It's built for Darwin right now. In order to build for the Linux kernel you have to set `GOOS=linux`.

**Comment by seeker89** [comment]
Good find, @xrl 👍  Do you have any bandwidth to push a fix ? 

There is also a multi-stage Dockerfile contributed via https://github.com/bloomberg/goldpinger/pull/18, but I think I'd like to keep both ways of building in the Makefile, at least for now, so this would still apply.
