### ISSUE TITLE
Add helm chart for easier deployment

### ISSUE THREAD

**Issue by XBeg9** [bloomberg/goldpinger#21]
Is there any plans to support helm charts? That would be perfect if we can deploy this thing using helm. Thanks

**Comment by seeker89** [comment]
That's a very good idea. It wasn't on our backlog, but it probably should. 👍

**Comment by twexler** [comment]
@seeker89 I'm currently working on this, but we need to figure out a place to host the images, as there's some internal concerns with that.

**Comment by marcosdiez** [comment]
I know this is not a full blown helm chart, but it kind of gives you the same results: https://github.com/bloomberg/goldpinger/pull/38

**Comment by seeker89** [comment]
> I know this is not a full blown helm chart, but it kind of gives you the same results: #38

Merged in 😄

**Comment by seeker89** [comment]
Ping. https://github.com/bloomberg/goldpinger/issues/27 is now resolved, and the images are being pushed to `bloomberg/goldpinger` on docker hub.

**Comment by okgolove** [comment]
Good news! 
As often happens, my previous PR to helm/charts was ignored.
I've recreated it and have used your docker repository.

https://github.com/helm/charts/pull/12205

**Comment by seeker89** [comment]
Awesome. The folks at helm do seem to have quite a bit on their plate, but hopefully they'll  merge it in.

**Comment by okgolove** [comment]
Yeah! The chart has been merged.

**Comment by okgolove** [comment]
Can somebody close the issue?

**Comment by seeker89** [comment]
Resolved
