### ISSUE TITLE
No license header in swagger-generated files

### ISSUE THREAD

**Issue by kaduev13** [bloomberg/goldpinger#32]
An execution of `$ make swagger` command generates go files without copyright header (and also, it removes this header from already existing files). It's not a big problem, but a bit annoying. What do you think about using [`swagger generate -r`](https://github.com/go-swagger/go-swagger/pull/1148) flag to add this copyright header to each generated file automatically? Another (more complicated) approach could be to override [default `go-swagger` templates](https://github.com/go-swagger/go-swagger/blob/master/docs/generate/templates.md).

**Comment by seeker89** [comment]
Very good point. TIL about [`swagger generate -r`](https://github.com/go-swagger/go-swagger/pull/1148) - thanks for that.

That's a great idea. We should just dump the copyright header into a `license.header` file, and update the Makefile to use the `-r` option.

Brilliant, thanks for the suggestion ! 👍

**Comment by kaduev13** [comment]
I played a little bit with this `-r` flag, and, unfortunately, it adds copyright right after the `// Code generated by go-swagger; DO NOT EDIT.` line.

Left side – master branch, right side – regenerated file with `license.header` and `swagger -r`.
![image](https://user-images.githubusercontent.com/3984307/50308798-a7e93a80-049c-11e9-914f-8c628fce916f.png)

This is how it works in default `go-swagger` templates (e.g. [server.gotmpl](https://github.com/go-swagger/go-swagger/blob/94886a08ebe16708d905b36452d457d7a69b907f/generator/templates/contrib/stratoscale/server/server.gotmpl)).

If such behavior is ok, then I can fill a PR. If not – I can create custom templates for `go-swagger` to override them.

**Comment by seeker89** [comment]
Thanks so much for volunteering this work, awesome @kaduev13 

Let me confirm, but I think that it should be fine. I'll get back to you on this.

**Comment by kpfleming** [comment]
You can do this if you wish, but there is no need for a copyright or license header on an autogenerated file; since it is machine generated, there is no copyright on its contents. If having the header will satisfy other processes or concerns, it's not harmful, though.
