### ISSUE TITLE
Offline usage

### ISSUE THREAD

**Issue by jpmondet** [bloomberg/goldpinger#39]
Hello !

First, thanks for this interesting project ! 

Maybe I did something wrong but it looks like the UI is not usable offline. 
I'm not a UI expert but it seems like it's trying to contact Cloudflare (and other CDNs) for some JS files, thus the UI is not fully working on an offline setup.

Would it be possible to embed those JS files needed by the [index.html](https://github.com/bloomberg/goldpinger/blob/master/static/index.html#L29) ? 
Or maybe add the steps in the Dockerfile to embed those files during the docker build ? 

Thanks in advance !

**Comment by seeker89** [comment]
Yep, you're right - they are currently just linked from a CDN. We could definitely embed it - download the files to `/static` folder, and change the references in the `/static/index.html` file.

Good idea 👍

**Comment by jpmondet** [comment]
Great, thanks ! I'll see if I can make it work and maybe submit a PR after that :-)

**Comment by seeker89** [comment]
This has been resolved via https://github.com/bloomberg/goldpinger/pull/44

Thanks @jpmondet !
