### ISSUE TITLE
Is there an easy way to change the label key

### ISSUE THREAD

**Issue by ficofer** [bloomberg/goldpinger#45]
Team,

Is there an easy way to change the way GP see other pods, in practice, make the label key `app` to something different?

Thanks!

**Comment by kaduev13** [comment]
Hi!

Looks like it's not documented, but such a feature was already introduced: https://github.com/bloomberg/goldpinger/commit/d93a43d68b5274b56d3220d3b206ed0986f0e78f

**Comment by ficofer** [comment]
@kaduev13 Thanks !! I try that, yes adding the label to the yaml of the daemon set ```LABEL_SELECTOR:  goldpinger=yes```

But it does not look to be grabbing it.

From what I see this was released in tag 1.1.0 that is the one I am using.

**Comment by seeker89** [comment]
Correct, thanks for the quick response @kaduev13 

@ficofer if you feel that this should be documented, please feel free to submit a PR to the README. Thanks ! 👍

**Comment by ficofer** [comment]
@seeker89 and @kaduev13 thanks for the answer!! 

Yes I will submit the PR with the Doc to set up the Label, but first I will like to make it work to be sure the README is ok!

I am trying to test the latest version of the code with master (building it locally) but with the build local image I get this issue is it related:

```➜  goldpinger git:(master) docker run --name gp -d goldpinger:1.2.0
719bde0d70f5d952a99aa08cdec3b53610ef3a418b74a7dcd01a0bb203b7e657
➜  goldpinger git:(master) docker logs 719bde0d70f5d952a99aa08cdec3b53610ef3a418b74a7dcd01a0bb203b7e657
standard_init_linux.go:190: exec user process caused "exec format error"
➜  goldpinger git:(master)```

I read something of the shebang missing in the `./build/Dockerfile-simple` but did not fix the issue.

Thanks!!!

**Comment by ficofer** [comment]
I was able to fix that adding this to the Makefile:

```
goos ?= linux```

But the new image running throws:

```2019/01/15 14:47:01 Updater ran into trouble with these peers:  [10.244.1.21 (10.138.31.100)]
2019/01/15 14:47:33 Updater ran into trouble with these peers:  [10.244.1.21 (10.138.31.100)]
2019/01/15 14:48:03 Updater ran into trouble with these peers:  [10.244.1.21 (10.138.31.100)]
2019/01/15 14:48:33 Updater ran into trouble with these peers:  [10.244.1.21 (10.138.31.100)]
2019/01/15 14:49:04 Updater ran into trouble with these peers:  [10.244.1.21 (10.138.31.100)]
2019/01/15 14:49:34 Updater ran into trouble with these peers:  [10.244.1.21 (10.138.31.100)]
2019/01/15 14:50:04 Updater ran into trouble with these peers:  [10.244.1.21 (10.138.31.100)]
2019/01/15 14:50:34 Updater ran into trouble with these peers:  [10.244.1.21 (10.138.31.100)]
2019/01/15 14:51:05 Updater ran into trouble with these peers:  [10.244.1.21 (10.138.31.100)]
2019/01/15 14:51:35 Updater ran into trouble with these peers:  [10.244.1.21 (10.138.31.100)]```

**Comment by seeker89** [comment]
How are you building it ? 

> I read something of the shebang missing in the `./build/Dockerfile-simple` but did not fix the issue.

What did you read and where ?

From the error message, it looks like you've built the binary for a different OS than you are running it on (macOS ?). In order to run in docker, it needs to be compiled for linux.

The easiest way to build it is through `make build-multistage`, which will build for linux.

Alternatively, you can use `GOOS` to override the binary OS when building, for example `GOOS=linux make bin/goldpinger` followed by `make build`. That said that should have been the default behavior, if you just run `make build`, so if you remove the binary, and just rerun `make build` it should work.

**Comment by ficofer** [comment]
I was able to fix that adding this to the Makefile:

```
goos ?= linux```

But the new image running throws:

```2019/01/15 14:47:01 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]
2019/01/15 14:47:33 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]
2019/01/15 14:48:03 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]
2019/01/15 14:48:33 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]
2019/01/15 14:49:04 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]
2019/01/15 14:49:34 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]
2019/01/15 14:50:04 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]
2019/01/15 14:50:34 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]
2019/01/15 14:51:05 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]
2019/01/15 14:51:35 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]```

**Comment by seeker89** [comment]
> `2019/01/15 14:47:33 Updater ran into trouble with these peers:  [10.244.1.21 (NODE_IP)]`

This means that it can't connect to the pod directly on the port that it's expecting, but it seems to be resolving it right. You'll need to check your networking policies, if any.
