### ISSUE TITLE
Also test if each node is resolving DNS properly?

### ISSUE THREAD

**Issue by marcosdiez** [bloomberg/goldpinger#46]
Somehow, today I created a new k8s cluster. With goldpinger I could easily check that all of them talk to each other, but it took me a lot of time to find out that one of the nodes was not resolving DNS. (all the others were).

I believe gold pinger would be the perfect tool to check that. It would also check if the nodes are talking to the outside world, which is also a great diagnostic.

**Comment by seeker89** [comment]
This sounds like a great idea to me. 👍 

I'm wondering what would be the best thing to periodically try to resolve.

**Comment by marcosdiez** [comment]
How about something to big to be affected like google.com or amazon.com ?
It could also be a setting.

**Comment by seeker89** [comment]
I think that in most cases, neither one of these should be resolvable from your production environment.
I guess we could add this as an option and let the user decide what to resolve.

**Comment by mzizzi** [comment]
> How about something to big to be affected like google.com or amazon.com ?
It could also be a setting.

I came here looking for this feature. :+1: on the feature and leaving the target hostname configurable.

**Comment by cgreen12** [comment]
I'm hoping to spend some time adding this over the next week or so.
