### ISSUE TITLE
Monitoring other endpoints?

### ISSUE THREAD

**Issue by vjanelle** [bloomberg/goldpinger#54]
Is there an option to check / graph other endpoints?

The general idea is that I'd like to check an external resource, like an external service.

**Comment by hipyhop** [comment]
I'm not sure about the future of goldpinger but this doesn't sound to me like what this project was intended for.

For external or blackbox monitoring we use blackbox_exporter and Prometheus to periodically ping sites and report on status. This supports http(s), DNS, TCP & ICMP.
There are also a number of Third party services like Pingdon and Route53 Health Checks that can hit publicly accessible endpoints.

**Comment by seeker89** [comment]
It has been suggested before, but since there are already tools doing that like @hipyhop mentioned, it's not currently planned.

Unless there is some really interesting use case, that isn't covered by what's already existing.

**Comment by vjanelle** [comment]
Well, by "external" I meant "externalName", and not necessarily public on the internet.  Pingdom and route53 health checks wouldn't apply here(is neither on the internet, nor on AWS, or exposing a Prometheus endpoint.)

**Comment by vjanelle** [comment]
Yup, that was my general thought.

**Comment by SleepyBrett** [comment]
@seeker89 I was just coming to ask for this feature. We've been running into a rare issue where something goes wrong with the networking stack and one of our nodes wouldn't nat traffic out. Having a blackbox exporter running would have a 1/<howevermanynodesihave> chance of catching that vs a deamonset.

**Comment by seeker89** [comment]
OK, I'd be glad to add a feature like this, but don't have bandwidth myself in the nearest future.
Any volunteers ?

**Comment by clly** [comment]
I'd be interested in trying to create an MR for this.

**Comment by seeker89** [comment]
> I'd be interested in trying to create an MR for this if you're still open to accepting it

Yup, definitely open to this. Note, that DNS is implemented, so I guess the scope here would be HTTP and ICMP?

**Comment by clly** [comment]
That sounds good with me.

**Comment by Nitive** [comment]
@vjanelle is it implemented or you don't need this functionality anymore?
