### ISSUE TITLE
Add liveness/readiness endpoints

### ISSUE THREAD

**Issue by dannyk81** [bloomberg/goldpinger#57]
I think this would be beneficial and will ensure accurate results, i.e. avoid false-positive due to some internal issue in one of the goldpinger pods.

**Comment by seeker89** [comment]
That's already implemented. See the swagger spec:

https://github.com/bloomberg/goldpinger/blob/86064f208ec99927b8dd9f717a93cbd22bb8b2fe/swagger.yml#L139-L158

We should probably update the example in README to add that in.

**Comment by dannyk81** [comment]
indeed! apologies for the noise, I will update my manifest accordingly.

**Comment by seeker89** [comment]
Actually, since you didn't find it, there is a good chance, that others won't either.

Would be so kind to add a PR to the README file with the health probe ? Thanks !

**Comment by dannyk81** [comment]
sure thing, see #58
