### ISSUE TITLE
Windows Container support

### ISSUE THREAD

**Issue by dorbeus** [bloomberg/goldpinger#66]
**Is your feature request related to a problem? Please describe.**
I'm testing running Kubernetes with Windows nodes, so of course i need this tool, but there is no instruction of how to build and run this in a Windows container.

**Describe the solution you'd like**
A instruction of how to build this on a windows container and preferably a pre-build container on docker-hub
A instruction of how to deploy this on a mixed Linux/Windows Kubernetes cluster.

**Describe alternatives you've considered**
Building this myself, but then i need to understand how go things are build.

**Additional context**

**Comment by seeker89** [comment]
It's a good point. I have no experience with Windows Containers, but I'd be happy to assist anyone who'd like to give it a shot.

**Comment by rbtr** [comment]
@seeker89 I'm willing to pick this feature up (because I would like to use it, ofc), but I will warn you up front that making multiplat images for Windows is a bit ugly 🙂

**Comment by seeker89** [comment]
That would be awesome!

**Comment by jkroepke** [comment]
I found some windows images on DockerHub (careful: random user), no github project linked: https://hub.docker.com/r/tylloyd/goldpinger

**Comment by rbtr** [comment]
@jkroepke that's @tyler-lloyd who was investigating implementing this. those are very unofficial dev/test images but are probably functional

**Comment by tyler-lloyd** [comment]
@jkroepke, @rbtr is right. very unofficial. here is the script I am working with right now. still figuring out how to contribute back to this project. currently running into issues with more recent verions of buildkit. https://github.com/tyler-lloyd/goldpinger/commit/521471175c1270c423a9c6b42be50ac06bee4c74

**Comment by jkroepke** [comment]
@tyler-lloyd please let me know if I can assists here. I need them soon and I would not like to copy and own docker images.

I hope @seeker89 and @skamboj are still open for the kind of feature.

**Comment by jkroepke** [comment]
Again, can I help here?

**Comment by tyler-lloyd** [comment]
@jkroepke - taking a look at your PR! thanks for picking this up!

**Comment by jkroepke** [comment]
@tyler-lloyd I found the blog artical which mention the cross OS builds for Windows. But instead using the shell scripts, I modernize the concept by using buildx bake

**Comment by tyler-lloyd** [comment]
I saw. The bake stuff is new to me so I'm interested to learn more about it. Do you have a test repository we can pull from that used your new ci tooling?

**Comment by jkroepke** [comment]
Sure:

https://github.com/cloudeteer/goldpinger/pkgs/container/goldpinger/143990577?tag=latest

ghcr.io/cloudeteer/goldpinger:latest

**Comment by tyler-lloyd** [comment]
hmm @jkroepke @skamboj I noticed the most recent version doesn't have the `v` prefix on the docker images? (it's `3.9.0` not `v3.9.0`) https://hub.docker.com/layers/bloomberg/goldpinger/3.9.0/images/sha256-955e43662647e650ef2f918f099e40bab2e0ac4d67c0855ae55652e852c581f6?context=explore

**Comment by jkroepke** [comment]
Whoops. Omit the v prefix on docker tags is very common. It's also the default behavior on the [metadata-action](https://github.com/docker/metadata-action?tab=readme-ov-file#typesemver). Sorry for this. I do not looked deeper on existing version.

In case the v prefix should be ensured, replace 

https://github.com/bloomberg/goldpinger/blob/0b96e45e05740a5da24354d05e5c46812b84c06d/.github/workflows/main.yml#L59

with

```
             type=semver,pattern={{raw}} 
```

Should add the `v` again
