### ISSUE TITLE
goldpinger UI fails if a node is in bad state.

### ISSUE THREAD

**Issue by kevinkim9264** [bloomberg/goldpinger#67]
**Describe the bug**
When I disable a node (i.e. manually stop a VM, or kills flanneld service, etc), I expect to see red mark on that particular node in goldpinger UI. However, the entire goldpinger UI fails. This happens even if I port-forward other goldpinger pods in healthy nodes. 

Is this an expected behavior? If so, doesn't it defeat the purpose of using goldpinger UI when a node is in bad state?

**To Reproduce**
1. Deploy goldpinger as daemonsets
2. Make a node unhealthy. (stops the VM, disables flanneld service, etc)
3. Try to load goldpinger UI. 

**Expected behavior**
Goldpinger UI loads and shows the red marks on the network paths to the affected node. 

**Screenshots**
When accessing via pod port-forwarding:
<img width="1675" alt="Screen Shot 2019-11-07 at 2 53 15 PM" src="https://user-images.githubusercontent.com/6677811/68434848-d8969900-016e-11ea-9977-62c7df6ed6e4.png">

When accessing via service:
<img width="1316" alt="Screen Shot 2019-11-07 at 2 56 39 PM" src="https://user-images.githubusercontent.com/6677811/68434864-de8c7a00-016e-11ea-9ea1-c687cc4206c2.png">

logs from still working goldpinger pod:
<img width="1673" alt="Screen Shot 2019-11-07 at 2 57 46 PM" src="https://user-images.githubusercontent.com/6677811/68434910-fa901b80-016e-11ea-8ad6-f2e198b21f7f.png">

**Environment (please complete the following information):**
 - Operating System and Version: [e.g. Ubuntu Linux 18.04]
 - Browser [e.g. Firefox, Safari] (if applicable):
Tried in Chrome and Safari

**Additional context**

** Deployment configuration **
```
{
  apiVersion: "apps/v1",
  kind: "DaemonSet",
  metadata: {
    name: "goldpinger",
    namespace: "goldpinger",
    labels: {
      app: "goldpinger",
    },
  },
  spec: {
    updateStrategy: {
      type: "RollingUpdate",
    },
    selector: {
      matchLabels: {
        app: "goldpinger",
      },
    },
    template: {
      metadata: {
        labels: {
          app: "goldpinger",
        },
      },
      spec: {
        serviceAccount: "goldpinger",
        containers: [
          {
            name: "goldpinger",
            env: [
              {
                name: "HOST",
                value: "0.0.0.0",
              },
              {
                name: "PORT",
                value: "80",
              },
              {
                name: "HOSTNAME",
                valueFrom: {
                  fieldRef: {
                    fieldPath: "spec.nodeName",
                  },
                },
              },
            ],
            image: "docker.io/bloomberg/goldpinger:2.0.0",
            ports: [
              {
                containerPort: 80,
                name: "http",
              },
            ],
          },
        ],
      },
    },
  },
}
```

**Comment by kevinkim9264** [comment]
For more info, this is the case where ping would hang, instead of immediately returning error code. Will that be a possible reason why the UI just hangs and doesn't show?

**Comment by seeker89** [comment]
This looks like a regression. Will try to reproduce and report back.

**Comment by seeker89** [comment]
Could you paste a sample output from a call to `/check_all` ? That would help debugging. Thanks!

**Comment by seeker89** [comment]
OK, I could reproduce the behaviour. Would you like to take https://github.com/bloomberg/goldpinger/pull/68 for a spin and confirm it works in your case?

**Comment by kevinkim9264** [comment]
@seeker89  thank you! will try it and let you know

**Comment by kevinkim9264** [comment]
@seeker89 unfortunately the problem persists. The behavior is a little different though: 
instead of throwing weird error, it just hangs and shows white page.

**Comment by kevinkim9264** [comment]
`/check_all` would show this result after some time:
```
{"hosts":[{"hostIP":"10.120.252.11","podIP":"10.2.97.146"},{"hostIP":"10.120.252.13","podIP":"10.2.96.83"},{"hostIP":"10.120.252.12","podIP":"10.2.66.71"},{"hostIP":"10.120.252.10","podIP":"10.2.117.162"},{"hostIP":"10.120.252.14","podIP":"10.2.89.70"},{"hostIP":"10.120.252.15","podIP":"10.2.2.91"},{"hostIP":"10.120.252.18","podIP":"10.2.123.96"},{"hostIP":"10.120.252.17","podIP":"10.2.92.81"},{"hostIP":"10.120.252.16","podIP":"10.2.54.83"}],"responses":{"10.2.117.162":{"HostIP":"10.120.252.10","OK":false,"error":"Get http://10.2.117.162:80/check: context deadline exceeded"},"10.2.123.96":{"HostIP":"10.120.252.18","OK":false,"error":"Get http://10.2.123.96:80/check: context deadline exceeded"},"10.2.2.91":{"HostIP":"10.120.252.15","OK":false,"error":"Get http://10.2.2.91:80/check: context deadline exceeded"},"10.2.54.83":{"HostIP":"10.120.252.16","OK":false,"error":"Get http://10.2.54.83:80/check: context deadline exceeded"},"10.2.66.71":{"HostIP":"10.120.252.12","OK":false,"error":"Get http://10.2.66.71:80/check: context deadline exceeded"},"10.2.89.70":{"HostIP":"10.120.252.14","OK":false,"error":"Get http://10.2.89.70:80/check: context deadline exceeded"},"10.2.92.81":{"HostIP":"10.120.252.17","OK":false,"error":"Get http://10.2.92.81:80/check: context deadline exceeded"},"10.2.96.83":{"HostIP":"10.120.252.13","OK":false,"error":"Get http://10.2.96.83:80/check: context deadline exceeded"},"10.2.97.146":{"HostIP":"10.120.252.11","OK":false,"error":"Get http://10.2.97.146:80/check: context deadline exceeded"}}}
```

**Comment by kevinkim9264** [comment]
The behavior in safari is also different, as it throws error:
<img width="1329" alt="Screen Shot 2019-11-08 at 9 29 49 AM" src="https://user-images.githubusercontent.com/6677811/68497848-5956a300-020a-11ea-9c41-31fa79109d70.png">

**Comment by kevinkim9264** [comment]
Ok. So it works properly if a pod is in bad state. (manually making a goldpinger pod in invalid state). However, if a node's networking is messed up (i.e. ping hangs, instead of returning error right away), then goldpinger UI would hang.

**Comment by seeker89** [comment]
Thanks for taking it for a spin. In that case we should tweak the logic displaying things, when there is not enough data. I should be able to sit down to it next week. Cheers!

**Comment by kevinkim9264** [comment]
@seeker89  thank you again for the quick response! I will look forward to the fix :)

**Comment by kevinkim9264** [comment]
@seeker89 did you get any chance to fix this issue? thank you

**Comment by seeker89** [comment]
Sorry, haven't gotten to that yet.

**Comment by kristoflemmens** [comment]
Him any update on this. Maybe I can help. Haven't got any experience with this but why not learn.

**Comment by seeker89** [comment]
@kristoflemmens that would be great and much appreciated. I haven't been able to find time since November!

**Comment by Leen15** [comment]
Hi, any update?
