### ISSUE TITLE
Goldpinger starts so quickly it often gets pods without IPs

### ISSUE THREAD

**Issue by seeker89** [bloomberg/goldpinger#86]
Goldpinger starts quickly, which is good, but it has an interesting side effect: often when it first lists pods, kubernetes doesn't list their IPs. With the current implementation, it often takes 30 seconds to restart the updaters goroutines. During these initial 30 seconds, graph and metrics are unhealthy.

It would be good to enhance it, so that if the pods don't have IPs, we retry to get them quicker than on other kinds of errors.

**Comment by bavarianbidi** [comment]
We also detected this issue in the last couple of days where we updated a bunch of k8s clusters.
I guess it might be sufficient to only get goldpinger-pods which are in `running` state - currently all pods will be used as ping-target ([code](https://github.com/bloomberg/goldpinger/blob/294b8dda19a46062aa04398844c18339f43f3b82/pkg/goldpinger/k8s.go#L47))

are you accepting a PR if we implement a fix?

**Comment by seeker89** [comment]
Definitely 👍
