### ISSUE TITLE
Helm charts repo deprecation

### ISSUE THREAD

**Issue by okgolove** [bloomberg/goldpinger#93]
**Is your feature request related to a problem? Please describe.**
Due to [deprecating helm/charts repository](https://github.com/scottrigby/prometheus-helm-charts/pull/14) goldpinger helm chart should be moved somewhere. Do bloomberg maintainers want to create own repo for helm charts or put helm chart in the goldpinger repo?

**Describe the solution you'd like**
The chart should be moved to another repo.

**Describe alternatives you've considered**

**Additional context**

**Comment by okgolove** [comment]
Now it lives here https://github.com/okgolove/helm-charts/tree/master/stable/goldpinger

**Comment by rtzra** [comment]
> Now it lives here https://github.com/okgolove/helm-charts/tree/master/stable/goldpinger

You mean: https://github.com/okgolove/helm-charts/tree/master/charts/goldpinger

**Comment by okgolove** [comment]
@rtzra correct, I've changed the path.
